management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

  health:
    diskSpace.enabled: false
    mail.enabled: false
    refresh.enabled: false